# Generated by Django 2.2.7 on 2019-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200, unique=True)),
                ('track_name', models.CharField(max_length=200)),
                ('track_artist', models.CharField(max_length=200)),
                ('track_preview', models.CharField(max_length=300)),
                ('track_in_album', models.CharField(max_length=200)),
                ('track_album_art', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=500, unique=True)),
                ('displayname', models.CharField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
