# Generated by Django 2.2.7 on 2019-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='SpotifyUser', to='user.Song'),
        ),
    ]
